# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copywrite < Formula
  desc "copywrite -- utilities for managing copyright headers and license files for GitHub repos"
  homepage "https://github.com/hashicorp/copywrite"
  version "0.16.4"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.4/copywrite_0.16.4_darwin_x86_64.tar.gz"
      sha256 "623ecbeec3a72ce08445032fe407d61339cffcec1329a72315c87caecbacca86"

      def install
        bin.install "copywrite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.4/copywrite_0.16.4_darwin_arm64.tar.gz"
      sha256 "e9fd16ecc0fb7edc4346c3a8abc1eac78e5351b76ca93348f9b1613129628bdb"

      def install
        bin.install "copywrite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.4/copywrite_0.16.4_linux_arm64.tar.gz"
      sha256 "9c23953531bcff8d9aca45961546f0be8899b9109e2578ce73ff6bc591160530"

      def install
        bin.install "copywrite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.4/copywrite_0.16.4_linux_x86_64.tar.gz"
      sha256 "c299f830e6eef7e126a3c6ef99ac6f43a3c132d830c769e0d36fa347fa1af254"

      def install
        bin.install "copywrite"
      end
    end
  end

  test do
    system "#{bin}/copywrite --version"
  end
end
