# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copywrite < Formula
  desc "copywrite -- utilities for managing copyright headers and license files for GitHub repos"
  homepage "https://github.com/hashicorp/copywrite"
  version "0.24.0"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/hashicorp/copywrite/releases/download/v0.24.0/copywrite_0.24.0_darwin_x86_64.tar.gz"
      sha256 "c9dcc8c7e9f670cb93d8819dc1279fcccdee33dd917750fe37182c29d303f427"

      def install
        bin.install "copywrite"
      end
    end
    on_arm do
      url "https://github.com/hashicorp/copywrite/releases/download/v0.24.0/copywrite_0.24.0_darwin_arm64.tar.gz"
      sha256 "7a64433557c208d0ae62856ca8fa6ef0618d8a77daeaac0720491ab8baef8c22"

      def install
        bin.install "copywrite"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashicorp/copywrite/releases/download/v0.24.0/copywrite_0.24.0_linux_x86_64.tar.gz"
        sha256 "636d83178523c95199bc2c61ac83ed0f227df4e88452913bbc7e9087edf15429"

        def install
          bin.install "copywrite"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashicorp/copywrite/releases/download/v0.24.0/copywrite_0.24.0_linux_arm64.tar.gz"
        sha256 "b32264a6ac46a73f336cbb99d25b74ea11a079154090358318a90548c1ee2e88"

        def install
          bin.install "copywrite"
        end
      end
    end
  end

  test do
    system "#{bin}/copywrite --version"
  end
end
