# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copywrite < Formula
  desc "copywrite -- utilities for managing copyright headers and license files for GitHub repos"
  homepage "https://github.com/hashicorp/copywrite"
  version "0.16.5"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.5/copywrite_Darwin_arm64.tar.gz"
      sha256 "30dc35717e28d849953c77e3e6ae91ef71a5f1a83883433b1408d56aedaaa17d"

      def install
        bin.install "copywrite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.5/copywrite_Darwin_x86_64.tar.gz"
      sha256 "0d76c0ecb516e70cfb17cb50f5e6997140cf517d09f8af48576245a8584d045b"

      def install
        bin.install "copywrite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.5/copywrite_Linux_x86_64.tar.gz"
      sha256 "d45b217b73e9c9bf3f3c67d65b86f1cfc2ac680a61ec2cffd5acc7534420f1b8"

      def install
        bin.install "copywrite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashicorp/copywrite/releases/download/v0.16.5/copywrite_Linux_arm64.tar.gz"
      sha256 "a2a97d7ded78746164fa850d30004b66131e306677abf60ef37f2ef6c733a999"

      def install
        bin.install "copywrite"
      end
    end
  end

  test do
    system "#{bin}/copywrite --version"
  end
end
