# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformLs < Formula
  desc "Terraform Language Server"
  homepage "https://github.com/hashicorp/terraform-ls"
  version "0.12.1"
  bottle :unneeded

  if OS.mac?
    url "https://releases.hashicorp.com/terraform-ls/0.12.1/terraform-ls_0.12.1_darwin_amd64.zip"
    sha256 "57b2438382fe768f5f8e940b8c9962ff5c12ca425e214b9714dbf2aaf6c2be1a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://releases.hashicorp.com/terraform-ls/0.12.1/terraform-ls_0.12.1_linux_amd64.zip"
    sha256 "b798afc2abd658b1e1f50941df40a26c5e3803f8c5e0a9f8992d8a2d746ffc2a"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://releases.hashicorp.com/terraform-ls/0.12.1/terraform-ls_0.12.1_linux_arm.zip"
    sha256 "21ff6ecf91c7409c9c959d419ccedb7b365adedbc05e99eb61be778d429f9584"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://releases.hashicorp.com/terraform-ls/0.12.1/terraform-ls_0.12.1_linux_arm64.zip"
    sha256 "7d6e6f3fce12cfd6e628beb9a1b9d2b19d6551c766b136fa105d49f38ed89f3d"
  end

  conflicts_with "terraform-ls"

  def install
    bin.install "terraform-ls"
  end

  test do
    system "#{bin}/terraform-ls --version"
  end
end
