# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformLs < Formula
  desc "Terraform Language Server"
  homepage "https://github.com/hashicorp/terraform-ls"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://releases.hashicorp.com/terraform-ls/0.6.1/terraform-ls_0.6.1_darwin_amd64.zip"
    sha256 "b8dff432cc7938818a258e5b23e612977712371ae24758ee20317df37f26cec4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://releases.hashicorp.com/terraform-ls/0.6.1/terraform-ls_0.6.1_linux_amd64.zip"
      sha256 "d12baa14fb13a1c29f8d2041b168e9e9d9d4e1cb7aa32cdb0a5368ff926d27e3"
    end
  end
  
  conflicts_with "terraform-ls"

  def install
    bin.install "terraform-ls"
  end

  test do
    system "#{bin}/terraform-ls --version"
  end
end
