name: Merge PR

on:
  pull_request

jobs:
  merge-pr:
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: "Omar-Khawaja"

