name: Run go tests
# This workflow will run the lambda and formula tests on every commit
on:
  - push

jobs:
  go-tests:
    name: Run formula and lambda go tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Test formula_templater CLI
        run: |
          cd util/formula_templater && go test .
      -
        name: Test lambda 
        run: |
          cd util/lambda_trigger && go test .
