name: publish-homebrew-lambda
on:
  push:
    branches:
      - master
    paths:
      - "util/lambda_trigger/**" # only publish lambda when changing lambda code
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke homebrew lambda update workflow
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: homebrew-lambda-update.yml
          repo: hashicorp/releng-support
          ref: main
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
